# Generated by Django 3.0.6 on 2020-06-06 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayActivityUserList',
            fields=[
                ('id', models.TextField(default='', primary_key=True, serialize=False)),
                ('order_number', models.TextField(default='')),
                ('brach_type', models.TextField(default='')),
                ('full_name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('record_date_time', models.DateTimeField(auto_now=True)),
                ('activity_date', models.DateField(auto_now=True)),
                ('list', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='brach_lists.DayActivityUserList')),
            ],
        ),
    ]
