# Generated by Django 3.0.8 on 2020-08-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brach_lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('list', 'text')},
        ),
    ]
